# Generated by Django 3.2.6 on 2021-08-06 21:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='djangoclasses',
            managers=[
                ('classes', django.db.models.manager.Manager()),
            ],
        ),
    ]
